codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch:
      default:
        target: auto
        threshold: 0.5%

ignore:
  - "**/*.html"
  - "**/*.css"
  - "src/test-setup.ts"
  - "src/test.ts"
  - "src/polyfills.ts"
  - "src/main.ts"
  - "src/environments/**"
  - "**/*.spec.ts"

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false

