[[setup]]
= Setup

== Releases and Demos

Here you will find documentation for the latest release and the current snapshot,
as well as demos of HAL Explorer (with examples):

[cols='1,1,2',stripes=even]
|===
| Latest Release | 2.2.1 | https://toedter.github.io/hal-explorer/release/hal-explorer/#theme=Cosmo&uri=examples/examples.hal-forms.json[HAL Explorer Demo]
| Current Snapshot | 2.2.2-SNAPSHOT | https://toedter.github.io/hal-explorer/snapshot/hal-explorer/#theme=Cosmo&uri=examples/examples.hal-forms.json[HAL Explorer Demo]
|===

To explore your services with these HAL Explorer demos, they must enable CORS.
When you want to explore a Spring-based service (e.g., running on localhost), you can (temporarily) add a simple
https://gist.github.com/toedter/72d62b4bb4a25d229dc1f1342ae429ad[CORS Filter] to your service. For more options, see
the <<Development Server>> section.

You can also experiment with the latest snapshot version of HAL Explorer.

== Integration with Your Backends

If you want to use a released version of HAL Explorer in a Java-based project,
you can define a dependency to the HAL Explorer WebJar.

[source,xml,indent=0,role="primary"]
.Maven
----
<dependency>
    <groupId>org.webjars</groupId>
    <artifactId>hal-explorer</artifactId>
    <version>2.2.1</version>
</dependency>
----

[source,indent=0,role="secondary"]
.Gradle
----
runtimeOnly 'org.webjars:hal-explorer:2.2.1'
----

When you use the WebJar with Spring Boot, you can access HAL Explorer
in a web browser at `/webjars/hal-explorer/2.2.1/index.html`.

If you are using Spring Data REST, you can instead add a dependency like

[source,xml,indent=0,role="primary"]
.Maven
----
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-rest-hal-explorer</artifactId>
</dependency>
----

[source,indent=0,role="secondary"]
.Gradle
----
runtimeOnly 'org.springframework.data:spring-data-rest-hal-explorer'
----

When you use `spring-data-rest-hal-explorer`, you can access HAL Explorer in a web browser at `/`.

You can also download a zip-based https://github.com/toedter/hal-explorer/releases/download/v2.2.1/hal-explorer-2.2.1.zip[distribution] and deploy it on any web server.

The easiest way to integrate the upstream version of HAL Explorer into your backend is to clone this Git repository,
do a production build (see below), and then copy the content of the `dist/` folder to a location accessible by your backend server.
When you use Spring Boot, a good location in your project's source tree would be
`src/main/resources/static/hal-explorer`.

== Build

=== node.js

* Install the latest version of https://nodejs.org[node.js] and yarn (`npm i -g yarn`).
* Run `yarn build` to build the project in production mode.
* The build artifacts will be stored in the `dist/` directory.

=== Development Server

Run `yarn start` for a dev server. Navigate to http://localhost:4200/.
The app will automatically reload if you change any of the source files.
The development server has a built-in proxy configuration
so that all calls to `/api` are forwarded to `localhost:8080/api`.
This is convenient when you want to test a local server without having to deal with CORS.
If you run `yarn start:fs`, an additional file server is started on port 3000.
In the test-data directory, you will find some JSON examples. Try it out with the URL
http://localhost:4200/#uri=http://localhost:3000/movies.hal-forms.json.

=== Gradle/Java Build Support

If you have Java installed, you can also build the project with Gradle.
The Gradle build will install Node.js locally in the project directory.
Run `./gradlew build` (or just `gradlew build` under Windows) to build the project in production mode.
The build artifacts will be stored in the `dist/` directory.

=== Building the docs

You can build this documentation

* Windows: `gradlew doc`
** If you see errors regarding file encoding, try `gradlew doc -Dfile.encoding=UTF-8`
* Linux: `./gradlew doc`

=== Running Tests

* `yarn test` runs the unit test suite against your default browser.
* `yarn test:headless` runs the unit test suite against headless Chrome.
* `yarn e2e` runs the e2e test suite against default browsers (using Playwright).

Take a look at `package.json` for more test options.
