[[setup]]
= Setup

== Releases and Demos

Here you find the documentation for the latest release and the current snapshot,
as well as the latest release and the current snapshot of HAL Explorer:

[cols='1,1,2',stripes=even]
|===
| Latest Release | 0.16.0 | https://toedter.github.io/hal-explorer/release/hal-explorer[HAL Explorer Demo]
| Current Snapshot | 0.17.0-SNAPSHOT | https://toedter.github.io/hal-explorer/snapshot/hal-explorer/#theme=Cosmo&uri=https://raw.githubusercontent.com/toedter/hal-explorer/master/test-data/examples.hal-forms.json[HAL Explorer Demo]
|===

To explore your services with these HAL Explorer demos, they have to enable CORS.
When you want to explore a Spring-based service (e.g. running on localhost), you could (temporarily) add a simple
https://gist.github.com/toedter/72d62b4bb4a25d229dc1f1342ae429ad[CORS Filter] to your service. For more options, see
section <<Development Server>>.

You can also play with the latest snapshot version of HAL Explorer in running demos. The backends
are implemented with Spring. I host these demos at Heroku,
so please give them a bit of time to warm up (this might take up to 1 minute).

[cols='1,1,2',stripes=even]
|===
| For HAL: | https://chatty42.herokuapp.com/hal-explorer/index.html#theme=Cosmo&url=https://chatty42.herokuapp.com/api[Chatty API] | Spring Data REST Backend
| For HAL-FORMS: | http://hypermedia-movies-demo.herokuapp.com/hal-explorer/index.html#theme=Cosmo&uri=http://hypermedia-movies-demo.herokuapp.com/api/movies/1[Movies API] | Spring HATEOAS Backend
|===

== Integration with your Backends

If you want to use a released version of HAL Explorer in a Java-based project,
you could define a dependency to the HAL Explorer WebJar.

[source,xml,indent=0,role="primary"]
.Maven
----
<dependency>
    <groupId>org.webjars</groupId>
    <artifactId>hal-explorer</artifactId>
    <version>0.16.0</version>
</dependency>
----

[source,groovy,indent=0,role="secondary"]
.Gradle
----
implementation 'org.webjars:hal-explorer:0.16.0'
----

If you are using Spring Data REST, you could instead add a dependency like

[source,xml,indent=0,role="primary"]
.Maven
----
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-rest-hal-explorer</artifactId>
</dependency>
----

[source,groovy,indent=0,role="secondary"]
.Gradle
----
implementation 'org.springframework.data:spring-data-rest-hal-explorer'
----

Of course, you could always download a zip-based https://github.com/toedter/hal-explorer/releases/tag/v0.16.0[distribution] and put it on any Web server.

The easiest way to integrate the upstream version of HAL Explorer into your backend would be to clone this Git repo,
do a production build (see below) and then copy the content of the dist folder to a location accessible by your backend server.
When you use Spring Boot, a good location in your project's source tree would be
src/main/java/resources/static/hal-explorer.

== Build

=== node.js

** Install the latest version of https://nodejs.og[node.js] and yarn (`npm i -g yarn`).
** Run `yarn build` to build the project in production mode.
** The build artifacts will be stored in the `dist/` directory.

=== Development Server

Run `yarn start` for a dev server. Navigate to http://localhost:4200/.
The app will automatically reload if you change any of the source files.
The development server has a build-in proxy configuration
so that all calls to `/api` are forwarded to `localhost:8080/api`.
This is convenient when you want to test a local server without having to deal with CORS.
If you run `yarn startl`, an additional file server is started with port 3000.
In the test-data directory, you find some JSON examples. Try it out with the URL
http://localhost:4200/#uri=http://localhost:3000/movies.hal-forms.json.

=== Gradle/Java Build Support

If you have Java installed, you can also build the project with Gradle.
The Gradle build will install Node.js locally in the project directory.
Run `./gradlew build` (or just `gradlew build` under Windows) to build the project in production mode.
The build artifacts will be stored in the `dist/` directory.

=== Building the docs

You can build this documentation

** Windows: `gradlew doc -Dfile.encoding=UTF-8`
** Linux: `./gradlew doc`

=== Running Tests

* `yarn test` to run the unit test suite against your default browser.
* `yarn test-headless` to run the unit test suite against headless Chrome.
* `yarn e2e` to run the e2e test suite against your default browser.
* `yarn e2e-headless` to run the e2e test suite against headless Chrome.

Take a look at `package.json` for more test options.
